name: Bug report
description: "Report a bug with PDF++"
labels: ["bug"]
title: "[Bug] "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! <!--- Please note: we consider a problem as a bug only if it can be reproducible in the sandbox vault where only PDF++ (and other relevant plugins if any) are enabled. If this is not the case, ask a question in the GitHub Discussions: https://github.com/RyotaUshio/obsidian-pdf-plus/discussions --->
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: 'A clear and concise description of what the bug is.'
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: 'Describe the detailed steps to reproduce the behavior in the sandbox vault. If possible, attach a PDF file where you face the problem.'
      placeholder: |
        1. Go to '...'|
        2. Click on '....'|
        3. Scroll down to '....'|
        4. See error
    validations:
      required: true
  - type: textarea
    id: screen-capture
    attributes:
      label: Screen recordings or screenshots
      description: "Add screen recordings that capture the situation the bug is happening. If it's difficult, add screenshots instead."
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: obsidian-debug-info
    attributes:
      label: Obsidian debug info
      description: "From the command palette, run the command `Show debug info`. Then select `Copy to clipboard` and paste the result here."
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: pdf-plus-debug-info
    attributes:
      label: 'PDF++ debug info'
      description: "From the command palette, run the command `PDF++: Copy debug info`. Then paste the result here."
      placeholder:
      render: json
    validations:
      required: true
