name: Feature request
description: "Suggest an idea for this project."
labels: ["enhancement"]
title: "[FR] "
body:
  - type: markdown
    attributes:
      value: |
        Note: for the time being, it is unlikely that PDF++ will support handwritten annotation. [Learn more](https://github.com/RyotaUshio/obsidian-pdf-plus/discussions/42)
